ZABER_SERIAL_PORT_NAME = 'COM3'
# Use path only for Linux
ZABER_SERIAL_PORT_PATH = '/dev/' + ZABER_SERIAL_PORT_NAME

FILTER_WHEEL_PORT_NAME = 'COM4'
# Use path only for Linux
FITLER_WHEEL_PORT_PATH = '/dev/' + FILTER_WHEEL_PORT_NAME